INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (33, 584.00, 54, null, null, 'NTY', '48780E', 1, 18, 'Сайлентблок заднего продольного рычага ', 'Kortex', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (35, 932.00, 42, null, null, 'Kortex', '48780E', 1, 20, 'Сайлентблок задней продольной тяги
', '4U', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (36, 2442.00, 42, 1, 'Задняя подвеска', 'SH Auto Parts', '234500A', 1, 9, 'Продольный рычаг задний правый (в сборе)', 'Точка опоры', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (41, 2988.00, 20, null, null, null, '48770A', 1, 26, 'Тяга задняя поперечная ', 'Точка опоры', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (46, 454.00, 10, null, null, null, '48760E', 1, 31, 'Рычаг подвески', 'Точка опоры', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (48, 629.00, 7, null, null, null, '48760E', 1, 33, 'Сайлентблок
', 'Kortex', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (52, 499.00, 45, null, null, null, '48720A', 1, 43, 'Тяга поперечная', '4U', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (83, 516.00, 10, null, null, null, '48710A', 1, 53, 'Сайлентблок задней поперечной тяги', '4U', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (84, 583.00, 10, null, null, null, '48730F', 1, 54, 'Рычаг подвески', '4U', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (88, 336.00, 10, null, null, null, '48069', 1, 58, 'Рычаг передний левый', 'Kortex', 'Россия');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (1, 8670.00, 93, 1, 'Задняя подвеска', '48790', '48790', 1, 6, 'Верхний рычаг задний левый (в сборе)', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (2, 8596.00, 68, 1, 'Задняя подвеска', '48770A', '48770A', 1, 7, 'Верхний рычаг задний правый (в сборе)', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (3, 7527.00, 97, 1, 'Задняя подвеска', '48780E', '48780E', 1, 8, 'Продольный рычаг задний левый (в сборе)', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (4, 8521.00, 100, 1, 'Задняя подвеска', '48760E', '48760E', 1, 9, 'Продольный рычаг задний правый (в сборе)', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (5, 7521.00, 99, 1, 'Задняя подвеска', '48720A', '48720A', 1, 10, 'Рычаг задней подвески левый поперечный № 1', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (24, 10555.00, 100, 1, 'Задняя подвеска', '48740F', '48740F', 1, 11, 'Рычаг задней подвески левый № 2', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (25, 7521.00, 99, 1, 'Задняя подвеска', '48710A', '48710A', 1, 12, 'Рычаг задней подвески правый поперечный № 1', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (26, 9832.00, 100, 1, 'Задняя подвеска', '48730F', '48730F', 1, 13, 'Рычаг задней подвески правый № 2', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (27, 12896.00, 100, 2, 'Передняя подвеска', '48069', '48069', 1, 14, 'Рычаг передней подвески нижний левый № 1', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (28, 12693.00, 100, 2, 'Передняя подвеска', '48068', '48068', 1, 15, 'Рычаг передней подвески нижний левый № 1', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (31, 1020.00, 15, null, null, 'E
', '48780E', 11, 16, 'Рычаг подвески', 'SH Auto Parts', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (37, 781.00, 20, null, null, '00', '48790', 1, 21, 'Рычаг подвески ', 'SH Auto Parts', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (40, 2564.00, 41, null, null, null, '48770A', 1, 25, 'Рычаг подвески правый', 'ASVA', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (42, 2079.00, 54, null, null, null, '48770A', 1, 27, 'Рычаг подвески', 'SH Auto Parts', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (43, 446.00, 47, null, null, null, '48770A', 1, 28, 'Тяга поперечная задней подвески верхняя', 'Just Drive', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (53, 506.00, 77, null, null, null, '48720A', 1, 44, 'Рычаг задний', 'ASVA', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (55, 527.00, 12, 3, 'Привод колеса', '43410M', '43410M', 1, 63, 'Сальник переднего приводного вала, правый / Сальник хвостовика
', 'Toyota', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (76, 2807.00, 9, null, null, null, '48740F', 1, 46, 'Рычаг подвески', 'SH Auto Parts', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (77, 241.00, 6, null, null, null, '48740F', 1, 47, 'Рычаг задний поперечный нижний (под пружину)', 'ASVA', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (78, 1888.00, 10, null, null, null, '48740F', 1, 48, 'Сайлентблок заднего рычага', 'Just Drive', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (79, 446.00, 10, null, null, null, '48710A', 1, 49, 'Рычаг подвески', 'NTY', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (86, 2706.00, 10, null, null, null, '48730F', 1, 56, 'Сайлентблок заднего рычага', 'Just Drive', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (91, 520.00, 10, null, null, null, '48068', 1, 61, 'Рычаг передний правый', 'ASVA', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (94, 509.00, 99, null, null, null, '43410M', 1, 65, 'Сальник', 'ASVA', 'Корея');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (32, 4869.00, 42, null, null, 'Ashika', '48780E', 1, 17, 'Продольный рычаг задний левый', 'OHNO', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (34, 471.00, 84, null, null, 'Stellox', '48780E', 1, 19, 'Сайлентблок продольного рычага к цапфе', 'Ashika', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (38, 2317.00, 10, null, null, null, '48790', 1, 22, 'Тяга поперечная задней подвески верхняя', 'Optimal', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (39, 369.00, 2, null, null, null, '48790', 1, 23, 'Сайлентблок задней поперечной тяги', 'Lykmc', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (44, 369.00, 15, null, null, null, '48770A', 1, 29, 'Сайлентблок задней тяги', 'Fenox', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (45, 1684.00, 10, null, null, null, '48770A', 1, 30, 'Рычаг независимой подвески колес', 'Ashika', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (47, 5399.00, 8, null, null, null, '48760E', 1, 32, 'Сайлентблок заднего продольного рычага', 'OHNO', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (49, 1888.00, 25, null, null, null, '48720A', 1, 40, 'Рычаг подвески ', 'Ashika', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (50, 3171.00, 24, null, null, null, '48720A', 1, 41, 'Сайлентблок заднего поперечного рычага', 'Lykmc', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (51, 3515.00, 22, null, null, null, '48720A', 1, 42, 'Тяга подвески', 'Optimal', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (54, 2155.00, 77, null, null, null, '48720A', 1, 45, 'Сайлентблок задней поперечной тяги
', 'Tatsumi
', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (80, 3171.00, 10, null, null, null, '48710A', 1, 50, 'Тяга подвески', 'Stellox', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (81, 506.00, 10, null, null, null, '48710A', 1, 51, 'Тяга поперечная', 'Ashika', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (82, 2155.00, 10, null, null, null, '48710A', 1, 52, 'Рычаг задний', 'Optimal', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (85, 14987.00, 10, null, null, null, '48730F', 1, 55, 'Рычаг задний поперечный (под пружину)', 'Lykmc', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (87, 12379.00, 10, null, null, null, '48069', 1, 57, 'Рычаг подвески ', 'Tatsumi
', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (89, 2979.00, 10, null, null, null, '48069', 1, 59, 'Пыльник шаровой опоры', 'Optimal', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (90, 4107.00, 10, null, null, null, '48068', 1, 60, 'Рычаг подвески', 'Ashika', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (92, 657.00, 10, null, null, null, '48068', 1, 62, 'Пыльник шаровой опоры', 'Stellox', 'Китай');
INSERT INTO auto_market.v_detail_info (id, price, quantity, detail_group_list_id, detail_group_list_text_title, article, producer_detail_code, amount_in_package, detail_id, detail_name, producer_name, country_name) VALUES (93, 126.00, 10, null, null, null, '43410M', 1, 64, 'Сальник привода', 'Optimal', 'Китай');